controller_list:
  - name: fake_right_arm_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: right_arm_manipulator
    pose: right_arm_home_position